(in-package :cl-user)

(defpackage :cl-enet 
  (:use :cl :cffi)
  (:export 
   ;;functions
   :enet-initialize
   :enet-host-create
   :enet-host-service
   :enet-address-set-host
   :enet-host-connect
   :enet-packet-create
   :enet-peer-send
   :enet-packet-destroy
   :run-simple-server
   ;;enums
   :enet-packet-flag-reliable
   :enet-packet-flag-unsequenced
   :enet-packet-flag-no-allocate
   :enet-packet-flag-unreliable-fragment
   :enet-version-major
   :enet-socket-type
   :enet-socket-type-stream
   :enet-event-type
   :enet-event-type-none
   :enet-event-type-connect
   :enet-event-type-disconnect
   :enet-event-type-receive
   ;;structs
   :enet-address
   :enet-host
   :enet-event
   :enet-packet
   :enet-peer
   ;;enet-address slots
   :host
   :port
   ;;enet-host slots
   :socket
   :address
   :incoming-bandwidth
   :outgoing-bandwidth
   :bandwidth-throttle-epoch
   :mtu
   :random-seed
   :recalculate-bandwidth-limits
   :peers
   :peer-count
   :channel-limit
   :service-time
   :dispatch-queue
   :continue-sending
   :packet-size
   :header-flags
   :commands
   :command-count
   :buffers
   :buffer-count
   :checksum
   :compressor
   :packet-data
   :received-address
   :received-data
   :received-data-length
   :total-sent-data
   :total-sent-packets
   :total-received-data
   :total-received-packets
   ;;enet-event slots
   :event-type
   :peer
   :channel-id
   :data
   :packet
   ;;enet-packet slots
   :reference-count
   :flags
   :data
   :data-length
   :free-callback
   ;;enet-peer slots
   :dispatch-list
   :host
   :outgoing-peer-id
   :incoming-peer-id
   :connect-id
   :outgoing-session-id
   :incoming-session-id
   :address
   :data
   :state
   :channels
   :channel-count
   :incoming-bandwidth
   :outgoing-bandwidth
   :incoming-bandwidth-throttle-epoch
   :outgoing-bandwidth-throttle-epoch
   :incoming-data-total
   :outgoing-data-total
   :last-send-time
   :last-receive-time
   :next-timeout
   :earliest-timeout
   :packet-loss-epoch
   :packets-sent
   :packets-lost
   :packet-loss
   :packet-loss-variance
   :packet-throttle
   :packet-throttle-limit
   :packet-throttle-counter
   :packet-throttle-epoch
   :packet-throttle-acceleration
   :packet-throttle-deceleration
   :packet-throttle-interval
   :ping-interval
   :timeout-limit
   :timeout-minimum
   :timeout-maximum
   :last-round-trip-time
   :lowest-round-trip-time
   :last-round-trip-time-variance
   :highest-round-trip-time-variance
   :round-trip-time
   :round-trip-time-variance
   :mtu
   :window-size
   :reliable-data-in-transit
   :outgoing-reliable-sequence-number
   :acknowledgements
   :sent-reliable-commands
   :sent-unreliable-commands
   :outgoing-reliable-commands
   :outgoing-unreliable-commands
   :dispatched-commands
   :needs-dispatch
   :incoming-unsequenced-group
   :outgoing-unsequenced-group
   :unsequenced-window
   :event-data))

           